# Site settings
title: Magnus Skare
description: University portfolio by Magnus Skare
baseurl: ""
url: ""

# Sass
sass:
  sass_dir: _sass
  style: :compressed

# Build settings
markdown: kramdown
include: ['_case', '_page']

# Time zone
timezone: Europe/London